CREATE TABLE ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45),
  DESCRIPCION NVARCHAR2(255),
  ESTADO NVARCHAR2(1)
);

CREATE TABLE BENEFICIARIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUI NVARCHAR2(45),
  PASAPORTE NVARCHAR2(45),
  PRIMER_NOMBRE NVARCHAR2(45),
  SEGUNDO_NOMBRE NVARCHAR2(45),
  PRIMER_APELLIDO NVARCHAR2(45),
  SEGUNDO_APELLIDO NVARCHAR2(45),
  CELULAR NVARCHAR2(15),
  CORREO NVARCHAR2(80),
  SEXO NVARCHAR2(2),
  FECHA_NACIMIENTO DATE,
  ESTADO_CIVIL_ID NUMBER(11),
  ETNIA_ID NUMBER(11),
  INTERLOCUTOR NVARCHAR2(10),
  CREATED_AT DATE,
  UPDATED_AT DATE,
  DELETED_AT DATE,
  ESTADO NVARCHAR2(1)
);

CREATE UNIQUE INDEX CUI_UNIQUE
  ON BENEFICIARIOS (CUI);
CREATE INDEX FK_BENEFICIARIOS_ESTADOS_CIVILES1_IDX
  ON BENEFICIARIOS (ESTADO_CIVIL_ID);
CREATE INDEX FK_BENEFICIARIOS_ETNIAS1_IDX
  ON BENEFICIARIOS (ETNIA_ID);

CREATE TABLE BENEFICIARIOS_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  DETALLE_ACTIVIDAD_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  ESTADO NVARCHAR2(1)
);

CREATE INDEX FK_BENEFICIARIOS_ACTIVIDADES_BENEFICIARIOS1_IDX
  ON BENEFICIARIOS_ACTIVIDADES (BENEFICIARIO_ID);
CREATE INDEX FK_BENEFICIARIOS_ACTIVIDADES_ACTIVIDADES1_IDX
  ON BENEFICIARIOS_ACTIVIDADES (DETALLE_ACTIVIDAD_ID);

CREATE TABLE BENEFICIARIOS_CURSOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  DETALLE_CURSO_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  ESTADO NVARCHAR2(1)
);
CREATE INDEX FK_CURSOS_BENEFICIARIOS_BENEFICIARIOS1_IDX
  ON BENEFICIARIOS_CURSOS (BENEFICIARIO_ID);
CREATE INDEX FK_BENEFICIARIOS_CURSO_DETALLES_CURSOS1_IDX
  ON BENEFICIARIOS_CURSOS (DETALLE_CURSO_ID);

CREATE TABLE BENEFICIARIOS_MODULOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  MODULO_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  ESTADO NVARCHAR2(1)
);
CREATE INDEX FK_NIVELES_BENEFICIARIOS_NIVELES1_IDX
  ON BENEFICIARIOS_MODULOS (MODULO_ID);
CREATE INDEX FK_NIVELES_BENEFICIARIOS_BENEFICIARIOS1_IDX
  ON BENEFICIARIOS_MODULOS (BENEFICIARIO_ID);

CREATE TABLE BITACORA (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACCION NVARCHAR2(100),
  TABLA NVARCHAR2(100),
  DESCRIPCION NVARCHAR2(500),
  CREATED_AT DATE,
  USUARIO_ID NUMBER(11),
  BENEFICIARIO_ID NUMBER(11),
  IDENTIFICADOR NUMBER(11)
);
CREATE INDEX FK_BITACORA_USUARIOS1_IDX
  ON BITACORA (USUARIO_ID);
CREATE INDEX FK_BITACORA_BENEFICIARIOS1_IDX
  ON BITACORA (BENEFICIARIO_ID);

CREATE TABLE CURSOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(80),
  DESCRIPCION NVARCHAR2(500),
  ESTADO NVARCHAR2(1)
);

CREATE TABLE CURSOS_MODULOS (
  MODULO_ID NUMBER(11) NOT NULL,
  DETALLE_CURSO_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_NIVELES_CURSOS_NIVELES1_IDX
  ON CURSOS_MODULOS (MODULO_ID);
CREATE INDEX FK_CURSOS_MODULO_DETALLES_CURSOS1_IDX
  ON CURSOS_MODULOS (DETALLE_CURSO_ID);

CREATE TABLE DATOS_ACADEMICOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ESTABLECIMIENTO NVARCHAR2(100),
  TIPO NVARCHAR2(3),
  TITULO_CARRERA NVARCHAR2(100),
  ESCOLARIDAD_ID NUMBER(11) NOT NULL,
  BENEFICIARIO_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_DATOS_ACADEMICOS_ESCOLARIDADES1_IDX
  ON DATOS_ACADEMICOS (ESCOLARIDAD_ID);
CREATE INDEX FK_DATOS_ACADEMICOS_BENEFICIARIOS1_IDX
  ON DATOS_ACADEMICOS (BENEFICIARIO_ID);

CREATE TABLE DATOS_MEDICOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ENFERMEDADES_ALERGIAS NVARCHAR2(500),
  MEDICAMENTOS NVARCHAR2(500),
  DOSIS NVARCHAR2(150),
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  TIPO_SANGRE_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_DATOS_MEDICOS_BENEFICIARIOS1_IDX
  ON DATOS_MEDICOS (BENEFICIARIO_ID);
CREATE INDEX FK_DATOS_MEDICOS_TIPOS_SANGRE1_IDX
  ON DATOS_MEDICOS (TIPO_SANGRE_ID);

CREATE TABLE DEPARTAMENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE DEPENDENCIAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100)
);

CREATE TABLE DETALLES_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACTIVIDAD_ID NUMBER(11) NOT NULL,
  RESPONSABLE NVARCHAR2(100),
  DIRECCION NVARCHAR2(100),
  ZONA_ID NUMBER(11),
  DISTRITO_ID NUMBER(11),
  HORA_INICIO NVARCHAR2(10),
  HORA_FINAL NVARCHAR2(10),
  FECHA_INICIAL DATE,
  FECHA_FINAL DATE,
  COORDENADAS NVARCHAR2(100),
  TIPO_ACTIVIDAD_ID NUMBER(11) NOT NULL,
  ESTADO_ACTIVIDAD_ID NUMBER(11) NOT NULL,
  PROGRAMA_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_DETALLES_ACTIVIDADES_ACTIVIDADES1_IDX
  ON DETALLES_ACTIVIDADES (ACTIVIDAD_ID);
CREATE INDEX FK_DETALLES_ACTIVIDADES_ZONAS1_IDX
  ON DETALLES_ACTIVIDADES (ZONA_ID);
CREATE INDEX FK_DETALLES_ACTIVIDADES_DISTRITOS1_IDX
  ON DETALLES_ACTIVIDADES (DISTRITO_ID);
CREATE INDEX FK_DETALLES_ACTIVIDADES_TIPOS_ACTIVIDADES1
  ON DETALLES_ACTIVIDADES (TIPO_ACTIVIDAD_ID);
CREATE INDEX FK_DETALLES_ACTIVIDADES_ESTADOS_ACTIVIDADES1
  ON DETALLES_ACTIVIDADES (ESTADO_ACTIVIDAD_ID);
CREATE INDEX FK_DETALLES_ACTIVIDADES_PROGRAMAS1
  ON DETALLES_ACTIVIDADES (PROGRAMA_ID);

CREATE TABLE DETALLES_CURSOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SECCION NVARCHAR2(45),
  CAPACIDAD NUMBER(11),
  MODALIDAD NVARCHAR2(25),
  CURSO_ID NUMBER(11) NOT NULL,
  INSTRUCTOR_ID NUMBER(11) NOT NULL,
  SEDE_ID NUMBER(11) NOT NULL,
  HORARIO_ID NUMBER(11) NOT NULL,
  PROGRAMA_ID NUMBER(11) NOT NULL,
  TEMPORALIDAD_ID NUMBER(11) NOT NULL,
  ESTADO NVARCHAR2(1),
  FECHA_INICIAL DATE,
  FECHA_FINAL DATE,
  PUBLICO NVARCHAR2(1)
);
CREATE INDEX FK_DETALLES_CURSOS_CURSOS1_IDX
  ON DETALLES_CURSOS (CURSO_ID);
CREATE INDEX FK_DETALLES_CURSOS_INSTRUCTORES1_IDX
  ON DETALLES_CURSOS (INSTRUCTOR_ID);
CREATE INDEX FK_DETALLES_CURSOS_SEDES1_IDX
  ON DETALLES_CURSOS (SEDE_ID);
CREATE INDEX FK_DETALLES_CURSOS_HORARIOS1_IDX
  ON DETALLES_CURSOS (HORARIO_ID);
CREATE INDEX FK_DETALLES_CURSOS_PROGRAMAS1_IDX
  ON DETALLES_CURSOS (PROGRAMA_ID);
CREATE INDEX FK_DETALLES_CURSOS_TEMPORALIDADES1_IDX
  ON DETALLES_CURSOS (TEMPORALIDAD_ID);

CREATE TABLE DISTRITOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE DOMICILIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DIRECCION NVARCHAR2(500),
  MUNICIPIO_ID NUMBER(11) NOT NULL,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  ZONA_ID NUMBER(11),
  GRUPO_ZONA_ID NUMBER(11)
);
CREATE INDEX FK_DOMICILIOS_MUNICIPIOS1_IDX
  ON DOMICILIOS (MUNICIPIO_ID);
CREATE INDEX FK_DOMICILIOS_BENEFICIARIOS1_IDX
  ON DOMICILIOS (BENEFICIARIO_ID);
CREATE INDEX FK_DOMICILIOS_ZONAS1_IDX
  ON DOMICILIOS (ZONA_ID);
CREATE INDEX FK_DOMICILIOS_GRUPOS_ZONA1_IDX
  ON DOMICILIOS (GRUPO_ZONA_ID);

CREATE TABLE ESCOLARIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE ESTADOS_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE ESTADOS_CIVILES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE ETNIAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE GRUPOS_HABITACIONALES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(80)
);

CREATE TABLE GRUPOS_ZONAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DESCRIPCION NVARCHAR2(100),
  GRUPO_HABITACIONAL_ID NUMBER(11) NOT NULL,
  ZONA_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_GRUPOS_ZONA_GRUPOS_HABITACIONALES1_IDX
  ON GRUPOS_ZONAS (GRUPO_HABITACIONAL_ID);
CREATE INDEX FK_GRUPOS_ZONA_ZONAS1_IDX
  ON GRUPOS_ZONAS (ZONA_ID);

CREATE TABLE HORARIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  HORA_INICIAL NVARCHAR2(10),
  HORA_FINAL NVARCHAR2(10),
  LUN NVARCHAR2(4),
  MAR NVARCHAR2(4),
  MIE NVARCHAR2(4),
  JUE NVARCHAR2(4),
  VIE NVARCHAR2(4),
  SAB NVARCHAR2(4),
  DOM NVARCHAR2(4),
  ESTADO NVARCHAR2(1)
);

CREATE TABLE INSTRUCTORES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100),
  ESTADO NVARCHAR2(1)
);

CREATE TABLE MENUS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100)
);

CREATE TABLE MODULOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(80),
  DESCRIPCION NVARCHAR2(500),
  PROGRAMA_ID NUMBER(11) NOT NULL,
  ESTADO NVARCHAR2(1),
  FECHA_INICIAL DATE,
  FECHA_FINAL DATE,
  PUBLICO NVARCHAR2(1)
);
CREATE INDEX FK_NIVELES_PROGRAMAS_IDX
  ON MODULOS (PROGRAMA_ID);

CREATE TABLE MUNICIPIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45),
  DEPARTAMENTO_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_MUNICIPIOS_DEPARTAMENTOS1_IDX
  ON MUNICIPIOS (DEPARTAMENTO_ID);

CREATE TABLE PAGINAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITULO NVARCHAR2(80),
  LINK NVARCHAR2(80),
  ICON NVARCHAR2(45),
  ORDEN NUMBER(11),
  PAGINA_ID NUMBER(11)
);
CREATE INDEX FK_MENUS_MENUS1_IDX
  ON PAGINAS (PAGINA_ID);

CREATE TABLE PAGINAS_MENUS (
  PAGINA_ID NUMBER(11) NOT NULL,
  MENU_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_PAGINAS_MENUS_PAGINAS1_IDX
  ON PAGINAS_MENUS (PAGINA_ID);
CREATE INDEX FK_PAGINAS_MENUS_MENUS1_IDX
  ON PAGINAS_MENUS (MENU_ID);

CREATE TABLE PARENTESCOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE PERFILES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100),
  ROL_ID NUMBER(11) NOT NULL,
  MENU_ID NUMBER(11) NOT NULL,
  DESCRIPCION NVARCHAR2(255)
);
CREATE INDEX FK_PERFILES_ROLES1_IDX
  ON PERFILES (ROL_ID);
CREATE INDEX FK_PERFILES_MENUS1_IDX
  ON PERFILES (MENU_ID);

CREATE TABLE PERMISOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(80),
  DESCRIPCION NVARCHAR2(255),
  APP NVARCHAR2(80),
  GRUPO NVARCHAR2(80)
);

CREATE TABLE PERMISOS_ROLES (
  PERMISO_ID NUMBER(11) NOT NULL,
  ROL_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_PERMISOS_ROLES_PERMISOS1_IDX
  ON PERMISOS_ROLES (PERMISO_ID);
CREATE INDEX FK_PERMISOS_ROLES_ROLES1_IDX
  ON PERMISOS_ROLES (ROL_ID);

CREATE TABLE PROGRAMAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(80),
  DESCRIPCION NVARCHAR2(255),
  DEPENDENCIA_ID NUMBER(11) NOT NULL,
  ESTADO NVARCHAR2(1)
);
CREATE INDEX FK_PROGRAMAS_DEPENDENCIAS1_IDX
  ON PROGRAMAS (DEPENDENCIA_ID);

CREATE TABLE REQUISITOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(80),
  ESTADO NVARCHAR2(1)
);

CREATE TABLE REQUISITOS_CURSOS (
  REQUISITO_ID NUMBER(11) NOT NULL,
  DETALLE_CURSO_ID NUMBER(11) NOT NULL,
  OBLIGATORIO NVARCHAR2(1)
);
CREATE INDEX FK_REQUISITOS_CURSOS_REQUISITOS1_IDX
  ON REQUISITOS_CURSOS (REQUISITO_ID);
CREATE INDEX FK_REQUISITOS_CURSOS_DETALLES_CURSOS1_IDX
  ON REQUISITOS_CURSOS (DETALLE_CURSO_ID);

CREATE TABLE REQUISITOS_MODULOS (
  MODULO_ID NUMBER(11) NOT NULL,
  REQUISITO_ID NUMBER(11) NOT NULL,
  OBLIGATORIO NVARCHAR2(1)
);
CREATE INDEX FK_REQUISITOS_MODULOS_MODULOS1_IDX
  ON REQUISITOS_MODULOS (MODULO_ID);
CREATE INDEX FK_REQUISITOS_MODULOS_REQUISITOS1_IDX
  ON REQUISITOS_MODULOS (REQUISITO_ID);

CREATE TABLE RESPONSABLES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUI NVARCHAR2(13),
  NOMBRE NVARCHAR2(150),
  CELULAR NVARCHAR2(12),
  EMAIL NVARCHAR2(60),
  SEXO NVARCHAR2(1),
  DIRECCION NVARCHAR2(200),
  CATEGORIA NVARCHAR2(1),
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  PARENTESCO_ID NUMBER(11) NOT NULL,
  ZONA_ID NUMBER(11)
);
CREATE INDEX FK_RESPONSABLES_BENEFICIARIOS1_IDX
  ON RESPONSABLES (BENEFICIARIO_ID);
CREATE INDEX FK_RESPONSABLES_PARENTESCOS1_IDX
  ON RESPONSABLES (PARENTESCO_ID);
CREATE INDEX FK_RESPONSABLES_ZONAS1_IDX
  ON RESPONSABLES (ZONA_ID);

CREATE TABLE ROLES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(60),
  DESCRIPCION NVARCHAR2(255)
);

CREATE TABLE SEDES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100),
  DIRECCION NVARCHAR2(100),
  DISTRITO_ID NUMBER(11),
  ZONA_ID NUMBER(11) NOT NULL,
  ESTADO NVARCHAR2(1)
);
CREATE INDEX FK_SEDES_DISTRITOS1_IDX
  ON SEDES (DISTRITO_ID);
CREATE INDEX FK_SEDES_ZONAS1_IDX
  ON SEDES (ZONA_ID);

CREATE TABLE TEMPORALIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE TIPOS_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE TIPOS_SANGRE (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(45)
);

CREATE TABLE USUARIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUI NVARCHAR2(13),
  NOMBRE NVARCHAR2(100),
  PASSWORD NVARCHAR2(512),
  DEPENDENCIA_ID NUMBER(11) NOT NULL,
  PERFIL_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  DELETED_AT DATE
);

CREATE UNIQUE INDEX CUI_UNIQUE_COPY_1
  ON USUARIOS (CUI);
CREATE INDEX FK_USUARIOS_DEPENDENCIAS1_IDX
  ON USUARIOS (DEPENDENCIA_ID);
CREATE INDEX FK_USUARIOS_PERFILES1_IDX
  ON USUARIOS (PERFIL_ID);

CREATE TABLE ZONAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DESCRIPCION NVARCHAR2(45)
);

CREATE TABLE TIPOS_EVENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100) NOT NULL,
);

CREATE TABLE ESTADOS_EVENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100) NOT NULL,
);

CREATE TABLE EVENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100) NOT NULL,
  DESCRIPCION NVARCHAR2(500),
  UBICACION NVARCHAR2(500),
  FECHA_INICIO DATE,
  FECHA_FINAL DATE,
  HORA_INI NVARCHAR2(20),
  HORA_FIN NVARCHAR2(20),
  RESPONSABLE NVARCHAR2(100),
  DURACION NVARCHAR2(200),
  CREATED_AT DATE,
  UPDATED_AT DATE,
  ESTADO_EVENTO_ID NUMBER(11) NOT NULL,
  TIPO_EVENTO_ID NUMBER(11) NOT NULL,
  DEPENDENCIA_ID NUMBER(11) NOT NULL,
  USUARIO_ID NUMBER(11) NOT NULL
);

CREATE TABLE CARRUSEL_IMAGENES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE NVARCHAR2(100) NOT NULL,
  LINK NVARCHAR2(100) NOT NULL,
  PATH NVARCHAR2(100) NOT NULL
);

ALTER TABLE BENEFICIARIOS ADD CONSTRAINT FK_BENEFICIARIOS_ESTADOS_CIVILES1 FOREIGN KEY (ESTADO_CIVIL_ID) REFERENCES ESTADOS_CIVILES (ID);
ALTER TABLE BENEFICIARIOS ADD CONSTRAINT FK_BENEFICIARIOS_ETNIAS1 FOREIGN KEY (ETNIA_ID) REFERENCES ETNIAS (ID);
ALTER TABLE BENEFICIARIOS_ACTIVIDADES ADD CONSTRAINT FK_BENEFICIARIOS_ACTIVIDADES_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BENEFICIARIOS_ACTIVIDADES ADD CONSTRAINT FK_BENEFICIARIOS_ACTIVIDADES_DETALLES_ACTIVIDADES1 FOREIGN KEY (DETALLE_ACTIVIDAD_ID) REFERENCES DETALLES_ACTIVIDADES (ID);
ALTER TABLE BENEFICIARIOS_CURSOS ADD CONSTRAINT FK_BENEFICIARIOS_CURSO_DETALLES_CURSOS1 FOREIGN KEY (DETALLE_CURSO_ID) REFERENCES DETALLES_CURSOS (ID);
ALTER TABLE BENEFICIARIOS_CURSOS ADD CONSTRAINT FK_CURSOS_BENEFICIARIOS_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BENEFICIARIOS_MODULOS ADD CONSTRAINT FK_NIVELES_BENEFICIARIOS_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BENEFICIARIOS_MODULOS ADD CONSTRAINT FK_NIVELES_BENEFICIARIOS_NIVELES1 FOREIGN KEY (MODULO_ID) REFERENCES MODULOS (ID);
ALTER TABLE BITACORA ADD CONSTRAINT FK_BITACORA_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BITACORA ADD CONSTRAINT FK_BITACORA_USUARIOS1 FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID);
ALTER TABLE CURSOS_MODULOS ADD CONSTRAINT FK_CURSOS_MODULO_DETALLES_CURSOS1 FOREIGN KEY (DETALLE_CURSO_ID) REFERENCES DETALLES_CURSOS (ID);
ALTER TABLE CURSOS_MODULOS ADD CONSTRAINT FK_NIVELES_CURSOS_NIVELES1 FOREIGN KEY (MODULO_ID) REFERENCES MODULOS (ID);
ALTER TABLE DATOS_ACADEMICOS ADD CONSTRAINT FK_DATOS_ACADEMICOS_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE DATOS_ACADEMICOS ADD CONSTRAINT FK_DATOS_ACADEMICOS_ESCOLARIDADES1 FOREIGN KEY (ESCOLARIDAD_ID) REFERENCES ESCOLARIDADES (ID);
ALTER TABLE DATOS_MEDICOS ADD CONSTRAINT FK_DATOS_MEDICOS_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE DATOS_MEDICOS ADD CONSTRAINT FK_DATOS_MEDICOS_TIPOS_SANGRE1 FOREIGN KEY (TIPO_SANGRE_ID) REFERENCES TIPOS_SANGRE (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DETALLES_ACTIVIDADES_ESTADOS_ACTIVIDADES1_COPY_1 FOREIGN KEY (ESTADO_ACTIVIDAD_ID) REFERENCES ESTADOS_ACTIVIDADES (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DETALLES_ACTIVIDADES_PROGRAMAS1_COPY_1 FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMAS (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DETALLES_ACTIVIDADES_TIPOS_ACTIVIDADES1_COPY_1 FOREIGN KEY (TIPO_ACTIVIDAD_ID) REFERENCES TIPOS_ACTIVIDADES (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DETALLES_ACTIVIDADES_ACTIVIDADES1 FOREIGN KEY (ACTIVIDAD_ID) REFERENCES ACTIVIDADES (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DETALLES_ACTIVIDADES_DISTRITOS1 FOREIGN KEY (DISTRITO_ID) REFERENCES DISTRITOS (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DETALLES_ACTIVIDADES_ZONAS1 FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DETALLES_CURSOS_CURSOS1 FOREIGN KEY (CURSO_ID) REFERENCES CURSOS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DETALLES_CURSOS_HORARIOS1 FOREIGN KEY (HORARIO_ID) REFERENCES HORARIOS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DETALLES_CURSOS_INSTRUCTORES1 FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORES (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DETALLES_CURSOS_PROGRAMAS1 FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMAS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DETALLES_CURSOS_SEDES1 FOREIGN KEY (SEDE_ID) REFERENCES SEDES (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DETALLES_CURSOS_TEMPORALIDADES1 FOREIGN KEY (TEMPORALIDAD_ID) REFERENCES TEMPORALIDADES (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_GRUPOS_ZONA1 FOREIGN KEY (GRUPO_ZONA_ID) REFERENCES GRUPOS_ZONAS (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_MUNICIPIOS1 FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIOS (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_ZONAS1 FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE GRUPOS_ZONAS ADD CONSTRAINT FK_GRUPOS_ZONA_GRUPOS_HABITACIONALES1 FOREIGN KEY (GRUPO_HABITACIONAL_ID) REFERENCES GRUPOS_HABITACIONALES (ID);
ALTER TABLE GRUPOS_ZONAS ADD CONSTRAINT FK_GRUPOS_ZONA_ZONAS1 FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE MODULOS ADD CONSTRAINT FK_NIVELES_PROGRAMAS FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMAS (ID);
ALTER TABLE MUNICIPIOS ADD CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTOS1 FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS (ID);
ALTER TABLE PAGINAS ADD CONSTRAINT FK_MENUS_MENUS1 FOREIGN KEY (PAGINA_ID) REFERENCES PAGINAS (ID);
ALTER TABLE PAGINAS_MENUS ADD CONSTRAINT FK_PAGINAS_MENUS_MENUS1 FOREIGN KEY (MENU_ID) REFERENCES MENUS (ID);
ALTER TABLE PAGINAS_MENUS ADD CONSTRAINT FK_PAGINAS_MENUS_PAGINAS1 FOREIGN KEY (PAGINA_ID) REFERENCES PAGINAS (ID);
ALTER TABLE PERFILES ADD CONSTRAINT FK_PERFILES_MENUS1 FOREIGN KEY (MENU_ID) REFERENCES MENUS (ID);
ALTER TABLE PERFILES ADD CONSTRAINT FK_PERFILES_ROLES1 FOREIGN KEY (ROL_ID) REFERENCES ROLES (ID);
ALTER TABLE PERMISOS_ROLES ADD CONSTRAINT FK_PERMISOS_ROLES_PERMISOS1 FOREIGN KEY (PERMISO_ID) REFERENCES PERMISOS (ID);
ALTER TABLE PERMISOS_ROLES ADD CONSTRAINT FK_PERMISOS_ROLES_ROLES1 FOREIGN KEY (ROL_ID) REFERENCES ROLES (ID);
ALTER TABLE PROGRAMAS ADD CONSTRAINT FK_PROGRAMAS_DEPENDENCIAS1 FOREIGN KEY (DEPENDENCIA_ID) REFERENCES DEPENDENCIAS (ID);
ALTER TABLE REQUISITOS_CURSOS ADD CONSTRAINT FK_REQUISITOS_CURSOS_DETALLES_CURSOS1 FOREIGN KEY (DETALLE_CURSO_ID) REFERENCES DETALLES_CURSOS (ID);
ALTER TABLE REQUISITOS_CURSOS ADD CONSTRAINT FK_REQUISITOS_CURSOS_REQUISITOS1 FOREIGN KEY (REQUISITO_ID) REFERENCES REQUISITOS (ID);
ALTER TABLE REQUISITOS_MODULOS ADD CONSTRAINT FK_REQUISITOS_MODULOS_MODULOS1 FOREIGN KEY (MODULO_ID) REFERENCES MODULOS (ID);
ALTER TABLE REQUISITOS_MODULOS ADD CONSTRAINT FK_REQUISITOS_MODULOS_REQUISITOS1 FOREIGN KEY (REQUISITO_ID) REFERENCES REQUISITOS (ID);
ALTER TABLE RESPONSABLES ADD CONSTRAINT FK_RESPONSABLES_BENEFICIARIOS1 FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE RESPONSABLES ADD CONSTRAINT FK_RESPONSABLES_PARENTESCOS1 FOREIGN KEY (PARENTESCO_ID) REFERENCES PARENTESCOS (ID);
ALTER TABLE RESPONSABLES ADD CONSTRAINT FK_RESPONSABLES_ZONAS1 FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE SEDES ADD CONSTRAINT FK_SEDES_DISTRITOS1 FOREIGN KEY (DISTRITO_ID) REFERENCES DISTRITOS (ID);
ALTER TABLE SEDES ADD CONSTRAINT FK_SEDES_ZONAS1 FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_DEPENDENCIAS1 FOREIGN KEY (DEPENDENCIA_ID) REFERENCES DEPENDENCIAS (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_PERFILES1 FOREIGN KEY (PERFIL_ID) REFERENCES PERFILES (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_ESTADOS_EVENTOS1 FOREIGN KEY (ESTADO_EVENTO_ID) REFERENCES ESTADOS_EVENTOS (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_TIPOS_EVENTOS1 FOREIGN KEY (TIPO_EVENTO_ID) REFERENCES TIPOS_EVENTOS (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_DEPENDENCIAS1 FOREIGN KEY (DEPENDENCIA_ID) REFERENCES DEPENDENCIAS (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_USUARIOS1 FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID);


