CREATE TABLE ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45),
  DESCRIPCION VARCHAR2(255),
  ESTADO VARCHAR2(1)
);

CREATE TABLE BENEFICIARIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUI VARCHAR2(45),
  PASAPORTE VARCHAR2(45),
  PRIMER_NOMBRE VARCHAR2(45),
  SEGUNDO_NOMBRE VARCHAR2(45),
  PRIMER_APELLIDO VARCHAR2(45),
  SEGUNDO_APELLIDO VARCHAR2(45),
  CELULAR VARCHAR2(15),
  CORREO VARCHAR2(80),
  SEXO VARCHAR2(2),
  FECHA_NACIMIENTO DATE,
  ESTADO_CIVIL_ID NUMBER(11),
  ETNIA_ID NUMBER(11),
  INTERLOCUTOR VARCHAR2(10),
  CREATED_AT DATE,
  UPDATED_AT DATE,
  DELETED_AT DATE,
  ESTADO VARCHAR2(1)
);

CREATE UNIQUE INDEX CUI_UNIQUE
  ON BENEFICIARIOS (CUI);
CREATE INDEX FK_BENEF_EST_CIV_IDX
  ON BENEFICIARIOS (ESTADO_CIVIL_ID);
CREATE INDEX FK_BENEF_ETNIAS_IDX
  ON BENEFICIARIOS (ETNIA_ID);

CREATE TABLE BENEFICIARIOS_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  DETALLE_ACTIVIDAD_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  ESTADO VARCHAR2(1)
);

CREATE INDEX FK_BENEF_ACT_BENEF_IDX
  ON BENEFICIARIOS_ACTIVIDADES (BENEFICIARIO_ID);
CREATE INDEX FK_BENEF_ACT_ACT_IDX
  ON BENEFICIARIOS_ACTIVIDADES (DETALLE_ACTIVIDAD_ID);

CREATE TABLE BENEFICIARIOS_CURSOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  DETALLE_CURSO_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  ESTADO VARCHAR2(1)
);
CREATE INDEX FK_CURSOS_BENEF_BENEFI_IDX
  ON BENEFICIARIOS_CURSOS (BENEFICIARIO_ID);
CREATE INDEX FK_BENEF_CUR_DET_CUR_IDX
  ON BENEFICIARIOS_CURSOS (DETALLE_CURSO_ID);

CREATE TABLE BENEFICIARIOS_MODULOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  MODULO_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  ESTADO VARCHAR2(1)
);
CREATE INDEX FK_NIV_BENEF_NIV_IDX
  ON BENEFICIARIOS_MODULOS (MODULO_ID);
CREATE INDEX FK_NIV_BENEF_BENEF_IDX
  ON BENEFICIARIOS_MODULOS (BENEFICIARIO_ID);

CREATE TABLE BITACORA (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACCION VARCHAR2(100),
  TABLA VARCHAR2(100),
  DESCRIPCION VARCHAR2(500),
  CREATED_AT DATE,
  USUARIO_ID NUMBER(11),
  BENEFICIARIO_ID NUMBER(11),
  IDENTIFICADOR NUMBER(11)
);
CREATE INDEX FK_BITACORA_USUARIOS_IDX
  ON BITACORA (USUARIO_ID);
CREATE INDEX FK_BITACORA_BENEFICIARIOS_IDX
  ON BITACORA (BENEFICIARIO_ID);

CREATE TABLE CURSOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  DESCRIPCION VARCHAR2(500),
  ESTADO VARCHAR2(1),
  IMPULSATEC VARCHAR2(1)
);

CREATE TABLE CURSOS_MODULOS (
  MODULO_ID NUMBER(11) NOT NULL,
  DETALLE_CURSO_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_NIVELES_CURSOS_NIVELES_IDX
  ON CURSOS_MODULOS (MODULO_ID);
CREATE INDEX FK_CUR_MOD_DET_CUR_IDX
  ON CURSOS_MODULOS (DETALLE_CURSO_ID);

CREATE TABLE DATOS_ACADEMICOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ESTABLECIMIENTO VARCHAR2(100),
  TIPO VARCHAR2(3),
  TITULO_CARRERA VARCHAR2(100),
  ESCOLARIDAD_ID NUMBER(11) NOT NULL,
  BENEFICIARIO_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_DATOS_ACADE_ESCOLA_IDX
  ON DATOS_ACADEMICOS (ESCOLARIDAD_ID);
CREATE INDEX FK_DATOS_ACADE_BENEF_IDX
  ON DATOS_ACADEMICOS (BENEFICIARIO_ID);

CREATE TABLE DATOS_MEDICOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ENFERMEDADES_ALERGIAS VARCHAR2(500),
  MEDICAMENTOS VARCHAR2(500),
  DOSIS VARCHAR2(150),
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  TIPO_SANGRE_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_DATOS_MEDICOS_BENEF_IDX
  ON DATOS_MEDICOS (BENEFICIARIO_ID);
CREATE INDEX FK_DATOS_MEDICOS_TIP_SANG_IDX
  ON DATOS_MEDICOS (TIPO_SANGRE_ID);

CREATE TABLE DEPARTAMENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE DEPENDENCIAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100)
);

CREATE TABLE DETALLES_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACTIVIDAD_ID NUMBER(11) NOT NULL,
  RESPONSABLE VARCHAR2(100),
  DIRECCION VARCHAR2(100),
  ZONA_ID NUMBER(11),
  DISTRITO_ID NUMBER(11),
  HORA_INICIO VARCHAR2(10),
  HORA_FINAL VARCHAR2(10),
  FECHA_INICIAL DATE,
  FECHA_FINAL DATE,
  COORDENADAS VARCHAR2(100),
  TIPO_ACTIVIDAD_ID NUMBER(11) NOT NULL,
  ESTADO_ACTIVIDAD_ID NUMBER(11) NOT NULL,
  PROGRAMA_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_DETALLES_ACT_ACT_IDX
  ON DETALLES_ACTIVIDADES (ACTIVIDAD_ID);
CREATE INDEX FK_DETALLES_ACT_ZON_IDX
  ON DETALLES_ACTIVIDADES (ZONA_ID);
CREATE INDEX FK_DETALLES_ACT_DISTR_IDX
  ON DETALLES_ACTIVIDADES (DISTRITO_ID);
CREATE INDEX FK_DETALLES_ACT_TIP_ACT_IDX
  ON DETALLES_ACTIVIDADES (TIPO_ACTIVIDAD_ID);
CREATE INDEX FK_DETALLES_ACT_EST_ACT_IDX
  ON DETALLES_ACTIVIDADES (ESTADO_ACTIVIDAD_ID);
CREATE INDEX FK_DETALLES_ACT_PROG_IDX
  ON DETALLES_ACTIVIDADES (PROGRAMA_ID);

CREATE TABLE DETALLES_CURSOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SECCION VARCHAR2(45),
  CAPACIDAD NUMBER(11),
  MODALIDAD VARCHAR2(25),
  CURSO_ID NUMBER(11) NOT NULL,
  INSTRUCTOR_ID NUMBER(11) NOT NULL,
  SEDE_ID NUMBER(11) NOT NULL,
  HORARIO_ID NUMBER(11) NOT NULL,
  PROGRAMA_ID NUMBER(11) NOT NULL,
  TEMPORALIDAD_ID NUMBER(11) NOT NULL,
  ESTADO VARCHAR2(1),
  FECHA_INICIAL DATE,
  FECHA_FINAL DATE,
  PUBLICO VARCHAR2(1)
);
CREATE INDEX FK_DETALLES_CUR_CUR_IDX
  ON DETALLES_CURSOS (CURSO_ID);
CREATE INDEX FK_DETALLES_CUR_INSTRUCT_IDX
  ON DETALLES_CURSOS (INSTRUCTOR_ID);
CREATE INDEX FK_DETALLES_CUR_SED_IDX
  ON DETALLES_CURSOS (SEDE_ID);
CREATE INDEX FK_DETALLES_CUR_HORA_IDX
  ON DETALLES_CURSOS (HORARIO_ID);
CREATE INDEX FK_DETALLES_CUR_PROG_IDX
  ON DETALLES_CURSOS (PROGRAMA_ID);
CREATE INDEX FK_DETALLES_CUR_TEMPO_IDX
  ON DETALLES_CURSOS (TEMPORALIDAD_ID);

CREATE TABLE DISTRITOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE DOMICILIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DIRECCION VARCHAR2(500),
  MUNICIPIO_ID NUMBER(11) NOT NULL,
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  ZONA_ID NUMBER(11),
  GRUPO_ZONA_ID NUMBER(11)
);
CREATE INDEX FK_DOMICILIOS_MUNI_IDX
  ON DOMICILIOS (MUNICIPIO_ID);
CREATE INDEX FK_DOMICILIOS_BENEF_IDX
  ON DOMICILIOS (BENEFICIARIO_ID);
CREATE INDEX FK_DOMICILIOS_ZONAS_IDX
  ON DOMICILIOS (ZONA_ID);
CREATE INDEX FK_DOMICILIOS_GRUPOS_ZONA_IDX
  ON DOMICILIOS (GRUPO_ZONA_ID);

CREATE TABLE ESCOLARIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE ESTADOS_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE ESTADOS_CIVILES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE ETNIAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE GRUPOS_HABITACIONALES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80)
);

CREATE TABLE GRUPOS_ZONAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DESCRIPCION VARCHAR2(100),
  GRUPO_HABITACIONAL_ID NUMBER(11) NOT NULL,
  ZONA_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_GRUPOS_ZONA_GRUPO_HABIT_IDX
  ON GRUPOS_ZONAS (GRUPO_HABITACIONAL_ID);
CREATE INDEX FK_GRUPOS_ZONA_ZONAS_IDX
  ON GRUPOS_ZONAS (ZONA_ID);

CREATE TABLE HORARIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  HORA_INICIAL VARCHAR2(10),
  HORA_FINAL VARCHAR2(10),
  LUN VARCHAR2(4),
  MAR VARCHAR2(4),
  MIE VARCHAR2(4),
  JUE VARCHAR2(4),
  VIE VARCHAR2(4),
  SAB VARCHAR2(4),
  DOM VARCHAR2(4),
  ESTADO VARCHAR2(1)
);

CREATE TABLE INSTRUCTORES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  ESTADO VARCHAR2(1)
);

CREATE TABLE MENUS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100)
);

CREATE TABLE MODULOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  DESCRIPCION VARCHAR2(500),
  PROGRAMA_ID NUMBER(11) NOT NULL,
  CAPACIDAD NUMBER(11),
  ESTADO VARCHAR2(1),
  FECHA_INICIAL DATE,
  FECHA_FINAL DATE,
  PUBLICO VARCHAR2(1)
);
CREATE INDEX FK_NIVELES_PROG_IDX
  ON MODULOS (PROGRAMA_ID);

CREATE TABLE MUNICIPIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45),
  DEPARTAMENTO_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_MUNICIPIOS_DEPART_IDX
  ON MUNICIPIOS (DEPARTAMENTO_ID);

CREATE TABLE PAGINAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TITULO VARCHAR2(80),
  LINK VARCHAR2(80),
  ICON VARCHAR2(45),
  ORDEN NUMBER(11),
  PAGINA_ID NUMBER(11)
);
CREATE INDEX FK_MENUS_MENUS_IDX
  ON PAGINAS (PAGINA_ID);

CREATE TABLE PAGINAS_MENUS (
  PAGINA_ID NUMBER(11) NOT NULL,
  MENU_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_PAG_MENUS_PAG_IDX
  ON PAGINAS_MENUS (PAGINA_ID);
CREATE INDEX FK_PAG_MENUS_MENUS_IDX
  ON PAGINAS_MENUS (MENU_ID);

CREATE TABLE PARENTESCOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE PERFILES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  ROL_ID NUMBER(11) NOT NULL,
  MENU_ID NUMBER(11) NOT NULL,
  DESCRIPCION VARCHAR2(255)
);
CREATE INDEX FK_PERFILES_ROLES_IDX
  ON PERFILES (ROL_ID);
CREATE INDEX FK_PERFILES_MENUS_IDX
  ON PERFILES (MENU_ID);

CREATE TABLE PERMISOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  DESCRIPCION VARCHAR2(255),
  APP VARCHAR2(80),
  GRUPO VARCHAR2(80)
);

CREATE TABLE PERMISOS_ROLES (
  PERMISO_ID NUMBER(11) NOT NULL,
  ROL_ID NUMBER(11) NOT NULL
);
CREATE INDEX FK_PERMISOS_ROLES_PERMISOS_IDX
  ON PERMISOS_ROLES (PERMISO_ID);
CREATE INDEX FK_PERMISOS_ROLES_ROLES_IDX
  ON PERMISOS_ROLES (ROL_ID);

CREATE TABLE PROGRAMAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  DESCRIPCION VARCHAR2(255),
  DEPENDENCIA_ID NUMBER(11) NOT NULL,
  ESTADO VARCHAR2(1)
);
CREATE INDEX FK_PROGRAMAS_DEPENDENCIAS_IDX
  ON PROGRAMAS (DEPENDENCIA_ID);

CREATE TABLE REQUISITOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80),
  ESTADO VARCHAR2(1)
);

CREATE TABLE REQUISITOS_CURSOS (
  REQUISITO_ID NUMBER(11) NOT NULL,
  DETALLE_CURSO_ID NUMBER(11) NOT NULL,
  OBLIGATORIO VARCHAR2(1)
);
CREATE INDEX FK_REQ_CURSOS_REQ_IDX
  ON REQUISITOS_CURSOS (REQUISITO_ID);
CREATE INDEX FK_REQ_CUR_DET_CUR_IDX
  ON REQUISITOS_CURSOS (DETALLE_CURSO_ID);

CREATE TABLE REQUISITOS_MODULOS (
  MODULO_ID NUMBER(11) NOT NULL,
  REQUISITO_ID NUMBER(11) NOT NULL,
  OBLIGATORIO VARCHAR2(1)
);
CREATE INDEX FK_REQ_MOD_MOD_IDX
  ON REQUISITOS_MODULOS (MODULO_ID);
CREATE INDEX FK_REQ_MOD_REQ_IDX
  ON REQUISITOS_MODULOS (REQUISITO_ID);

CREATE TABLE RESPONSABLES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUI VARCHAR2(13),
  NOMBRE VARCHAR2(150),
  CELULAR VARCHAR2(12),
  EMAIL VARCHAR2(60),
  SEXO VARCHAR2(1),
  DIRECCION VARCHAR2(200),
  CATEGORIA VARCHAR2(1),
  BENEFICIARIO_ID NUMBER(11) NOT NULL,
  PARENTESCO_ID NUMBER(11) NOT NULL,
  ZONA_ID NUMBER(11)
);
CREATE INDEX FK_RESP_BENEF_IDX
  ON RESPONSABLES (BENEFICIARIO_ID);
CREATE INDEX FK_RESP_PARENTESCOS_IDX
  ON RESPONSABLES (PARENTESCO_ID);
CREATE INDEX FK_RESPONSABLES_ZONAS_IDX
  ON RESPONSABLES (ZONA_ID);

CREATE TABLE ROLES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(60),
  DESCRIPCION VARCHAR2(255)
);

CREATE TABLE SEDES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  DIRECCION VARCHAR2(100),
  DISTRITO_ID NUMBER(11),
  ZONA_ID NUMBER(11) NOT NULL,
  ESTADO VARCHAR2(1)
);
CREATE INDEX FK_SEDES_DISTRITOS_IDX
  ON SEDES (DISTRITO_ID);
CREATE INDEX FK_SEDES_ZONAS_IDX
  ON SEDES (ZONA_ID);

CREATE TABLE TEMPORALIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE TIPOS_ACTIVIDADES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE TIPOS_SANGRE (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(45)
);

CREATE TABLE USUARIOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUI VARCHAR2(13),
  NOMBRE VARCHAR2(100),
  PASSWORD VARCHAR2(512),
  DEPENDENCIA_ID NUMBER(11) NOT NULL,
  PERFIL_ID NUMBER(11) NOT NULL,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  DELETED_AT DATE
);

CREATE UNIQUE INDEX CUI_UNIQUE_1
  ON USUARIOS (CUI);
CREATE INDEX FK_USUARIOS_DEP_IDX
  ON USUARIOS (DEPENDENCIA_ID);
CREATE INDEX FK_USUARIOS_PERFILES_IDX
  ON USUARIOS (PERFIL_ID);

CREATE TABLE ZONAS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DESCRIPCION VARCHAR2(45)
);

CREATE TABLE TIPOS_EVENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE ESTADOS_EVENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE EVENTOS (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  DESCRIPCION VARCHAR2(500),
  UBICACION VARCHAR2(500),
  FECHA_INICIO DATE,
  FECHA_FINAL DATE,
  HORA_INI VARCHAR2(20),
  HORA_FIN VARCHAR2(20),
  RESPONSABLE VARCHAR2(100),
  CREATED_AT DATE,
  UPDATED_AT DATE,
  ESTADO_EVENTO_ID NUMBER(11) NOT NULL,
  TIPO_EVENTO_ID NUMBER(11) NOT NULL,
  DEPENDENCIA_ID NUMBER(11) NOT NULL,
  USUARIO_ID NUMBER(11) NOT NULL
);

CREATE TABLE CARRUSEL_IMAGENES (
  ID NUMBER(11) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  LINK VARCHAR2(100) NOT NULL,
  PATH VARCHAR2(100) NOT NULL
);

ALTER TABLE BENEFICIARIOS ADD CONSTRAINT FK_BENEFICIARIOS_EST_CIV FOREIGN KEY (ESTADO_CIVIL_ID) REFERENCES ESTADOS_CIVILES (ID);
ALTER TABLE BENEFICIARIOS ADD CONSTRAINT FK_BENEFICIARIOS_ETNIAS FOREIGN KEY (ETNIA_ID) REFERENCES ETNIAS (ID);
ALTER TABLE BENEFICIARIOS_ACTIVIDADES ADD CONSTRAINT FK_BENEF_ACT_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BENEFICIARIOS_ACTIVIDADES ADD CONSTRAINT FK_BENEF_ACT_DET_ACT FOREIGN KEY (DETALLE_ACTIVIDAD_ID) REFERENCES DETALLES_ACTIVIDADES (ID);
ALTER TABLE BENEFICIARIOS_CURSOS ADD CONSTRAINT FK_BENEF_CUR_DET_CUR FOREIGN KEY (DETALLE_CURSO_ID) REFERENCES DETALLES_CURSOS (ID);
ALTER TABLE BENEFICIARIOS_CURSOS ADD CONSTRAINT FK_CUR_BENEF_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BENEFICIARIOS_MODULOS ADD CONSTRAINT FK_NIV_BENEF_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BENEFICIARIOS_MODULOS ADD CONSTRAINT FK_NIV_BENEF_NIV FOREIGN KEY (MODULO_ID) REFERENCES MODULOS (ID);
ALTER TABLE BITACORA ADD CONSTRAINT FK_BITACORA_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE BITACORA ADD CONSTRAINT FK_BITACORA_USUARIOS FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID);
ALTER TABLE CURSOS_MODULOS ADD CONSTRAINT FK_CUR_MOD_DET_CUR FOREIGN KEY (DETALLE_CURSO_ID) REFERENCES DETALLES_CURSOS (ID);
ALTER TABLE CURSOS_MODULOS ADD CONSTRAINT FK_NIV_CUR_NIV FOREIGN KEY (MODULO_ID) REFERENCES MODULOS (ID);
ALTER TABLE DATOS_ACADEMICOS ADD CONSTRAINT FK_DATOS_ACADE_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE DATOS_ACADEMICOS ADD CONSTRAINT FK_DATOS_ACADE_ESCOLA FOREIGN KEY (ESCOLARIDAD_ID) REFERENCES ESCOLARIDADES (ID);
ALTER TABLE DATOS_MEDICOS ADD CONSTRAINT FK_DATOS_MEDICOS_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE DATOS_MEDICOS ADD CONSTRAINT FK_DATOS_MEDICOS_TIPOS_SANGRE FOREIGN KEY (TIPO_SANGRE_ID) REFERENCES TIPOS_SANGRE (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DET_ACT_ESTADOS_ACT FOREIGN KEY (ESTADO_ACTIVIDAD_ID) REFERENCES ESTADOS_ACTIVIDADES (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DET_ACT_PROG FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMAS (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DET_ACT_TIPOS_ACT FOREIGN KEY (TIPO_ACTIVIDAD_ID) REFERENCES TIPOS_ACTIVIDADES (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DET_ACT_ACT FOREIGN KEY (ACTIVIDAD_ID) REFERENCES ACTIVIDADES (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DET_ACT_DIST FOREIGN KEY (DISTRITO_ID) REFERENCES DISTRITOS (ID);
ALTER TABLE DETALLES_ACTIVIDADES ADD CONSTRAINT FK_DET_ACT_ZONAS FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DET_CUR_CUR FOREIGN KEY (CURSO_ID) REFERENCES CURSOS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DET_CUR_HORA FOREIGN KEY (HORARIO_ID) REFERENCES HORARIOS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DETA_CUR_INSTRUCTORES FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTORES (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DET_CUR_PROG FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMAS (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DET_CUR_SEDES FOREIGN KEY (SEDE_ID) REFERENCES SEDES (ID);
ALTER TABLE DETALLES_CURSOS ADD CONSTRAINT FK_DET_CUR_TEMPORALIDADES FOREIGN KEY (TEMPORALIDAD_ID) REFERENCES TEMPORALIDADES (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_GRUPOS_ZONA FOREIGN KEY (GRUPO_ZONA_ID) REFERENCES GRUPOS_ZONAS (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_MUNICIPIOS FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIOS (ID);
ALTER TABLE DOMICILIOS ADD CONSTRAINT FK_DOMICILIOS_ZONAS FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE GRUPOS_ZONAS ADD CONSTRAINT FK_GRUPOS_ZONA_GRUPOS_HABITA FOREIGN KEY (GRUPO_HABITACIONAL_ID) REFERENCES GRUPOS_HABITACIONALES (ID);
ALTER TABLE GRUPOS_ZONAS ADD CONSTRAINT FK_GRUPOS_ZONA_ZONAS FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE MODULOS ADD CONSTRAINT FK_NIVELES_PROGRAMAS FOREIGN KEY (PROGRAMA_ID) REFERENCES PROGRAMAS (ID);
ALTER TABLE MUNICIPIOS ADD CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS (ID);
ALTER TABLE PAGINAS ADD CONSTRAINT FK_MENUS_MENUS FOREIGN KEY (PAGINA_ID) REFERENCES PAGINAS (ID);
ALTER TABLE PAGINAS_MENUS ADD CONSTRAINT FK_PAGINAS_MENUS_MENUS FOREIGN KEY (MENU_ID) REFERENCES MENUS (ID);
ALTER TABLE PAGINAS_MENUS ADD CONSTRAINT FK_PAGINAS_MENUS_PAGINAS FOREIGN KEY (PAGINA_ID) REFERENCES PAGINAS (ID);
ALTER TABLE PERFILES ADD CONSTRAINT FK_PERFILES_MENUS FOREIGN KEY (MENU_ID) REFERENCES MENUS (ID);
ALTER TABLE PERFILES ADD CONSTRAINT FK_PERFILES_ROLES FOREIGN KEY (ROL_ID) REFERENCES ROLES (ID);
ALTER TABLE PERMISOS_ROLES ADD CONSTRAINT FK_PERMISOS_ROLES_PERMISOS FOREIGN KEY (PERMISO_ID) REFERENCES PERMISOS (ID);
ALTER TABLE PERMISOS_ROLES ADD CONSTRAINT FK_PERMISOS_ROLES_ROLES FOREIGN KEY (ROL_ID) REFERENCES ROLES (ID);
ALTER TABLE PROGRAMAS ADD CONSTRAINT FK_PROGRAMAS_DEPENDENCIAS FOREIGN KEY (DEPENDENCIA_ID) REFERENCES DEPENDENCIAS (ID);
ALTER TABLE REQUISITOS_CURSOS ADD CONSTRAINT FK_REQUISITOS_CUR_DET_CURSOS FOREIGN KEY (DETALLE_CURSO_ID) REFERENCES DETALLES_CURSOS (ID);
ALTER TABLE REQUISITOS_CURSOS ADD CONSTRAINT FK_REQUISITOS_CUR_REQUISITOS FOREIGN KEY (REQUISITO_ID) REFERENCES REQUISITOS (ID);
ALTER TABLE REQUISITOS_MODULOS ADD CONSTRAINT FK_REQUISITOS_MOD_MOD FOREIGN KEY (MODULO_ID) REFERENCES MODULOS (ID);
ALTER TABLE REQUISITOS_MODULOS ADD CONSTRAINT FK_REQUISITOS_MOD_REQUISITOS FOREIGN KEY (REQUISITO_ID) REFERENCES REQUISITOS (ID);
ALTER TABLE RESPONSABLES ADD CONSTRAINT FK_RESPONSABLES_BENEF FOREIGN KEY (BENEFICIARIO_ID) REFERENCES BENEFICIARIOS (ID);
ALTER TABLE RESPONSABLES ADD CONSTRAINT FK_RESPONSABLES_PARENTESCOS FOREIGN KEY (PARENTESCO_ID) REFERENCES PARENTESCOS (ID);
ALTER TABLE RESPONSABLES ADD CONSTRAINT FK_RESPONSABLES_ZONAS FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE SEDES ADD CONSTRAINT FK_SEDES_DISTRITOS FOREIGN KEY (DISTRITO_ID) REFERENCES DISTRITOS (ID);
ALTER TABLE SEDES ADD CONSTRAINT FK_SEDES_ZONAS FOREIGN KEY (ZONA_ID) REFERENCES ZONAS (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_DEPENDENCIAS FOREIGN KEY (DEPENDENCIA_ID) REFERENCES DEPENDENCIAS (ID);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_PERFILES FOREIGN KEY (PERFIL_ID) REFERENCES PERFILES (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_ESTADOS_EVENTOS FOREIGN KEY (ESTADO_EVENTO_ID) REFERENCES ESTADOS_EVENTOS (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_TIPOS_EVENTOS FOREIGN KEY (TIPO_EVENTO_ID) REFERENCES TIPOS_EVENTOS (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_DEPENDENCIAS FOREIGN KEY (DEPENDENCIA_ID) REFERENCES DEPENDENCIAS (ID);
ALTER TABLE EVENTOS ADD CONSTRAINT FK_EVENTOS_USUARIOS FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID);


